name: Deploy to Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
      ref:
        description: Git ref to deploy
        required: true
        default: develop

env:
  DOCKERHUB_REPOSITORY_BASE: dfedigital/meeting-timer

jobs:
  turnstyle:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: softprops/turnstyle@v1
        name: Check workflow concurrency
        with:
          poll-interval-seconds: 20
          same-branch-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: build docker image and deploy
    needs: turnstyle
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.0

      - name: Set environment variables
        id: set_env_vars
        run:
          echo "TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set dockerhub repo
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          if [[ "$ENVIRONMENT" == *"review"* ]]; then DOCKERHUB_ENV=dev; else DOCKERHUB_ENV=$ENVIRONMENT; fi
          echo "DOCKERHUB_ENV=$DOCKERHUB_ENV" >> $GITHUB_ENV
      - name: Build and push docker image from builder target
        uses: docker/build-push-action@v2
        with:
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: |
            ${{ env.DOCKERHUB_REPOSITORY_BASE }}${{ env.DOCKERHUB_ENV }}
          push: true
          tags: ${{ env.DOCKERHUB_REPOSITORY_BASE }}${{ env.DOCKERHUB_ENV }}

      - name: Deploy review app to dev
        if: ${{ startsWith(github.event.inputs.environment, 'review') }}
        env:
          TF_VAR_paas_user: ${{ secrets.GOVPAAS_DEV_USERNAME }}
          TF_VAR_paas_password: ${{ secrets.GOVPAAS_DEV_PASSWORD }}
        run: |
          export TF_VAR_paas_app_docker_image=${{ env.DOCKERHUB_REPOSITORY_BASE }}${{ env.DOCKERHUB_ENV }}:${{ env.TAG }}
          cd terraform/app
          terraform init -reconfigure -input=false
          terraform apply -input=false -auto-approve -var-file ../workspace-variables/review.tfvars -var='environment=${{github.event.inputs.environment}}'
